name: Makefile CI

on:
  push:
    branches: [ "v5.8.7" ]
  pull_request:
    branches: [ "v5.8.7" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure
      run: |
        echo $(uname -r)
        echo ${{ github.head_ref || github.ref_name }}
